//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MastControlPandur3.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MastControlPandur3.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available hw-ids: {0} ähnelt.
        /// </summary>
        internal static string CANAvailableHWIDs {
            get {
                return ResourceManager.GetString("CANAvailableHWIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected ähnelt.
        /// </summary>
        internal static string CANConnected {
            get {
                return ResourceManager.GetString("CANConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecting... ähnelt.
        /// </summary>
        internal static string CANConnecting {
            get {
                return ResourceManager.GetString("CANConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device with hw-id {0} not found! ähnelt.
        /// </summary>
        internal static string CANDeviceNotFound {
            get {
                return ResourceManager.GetString("CANDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnected ähnelt.
        /// </summary>
        internal static string CANDisconnected {
            get {
                return ResourceManager.GetString("CANDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnecting... ähnelt.
        /// </summary>
        internal static string CANDisconnecting {
            get {
                return ResourceManager.GetString("CANDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die none ähnelt.
        /// </summary>
        internal static string CANEmptyDeviceList {
            get {
                return ResourceManager.GetString("CANEmptyDeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die acknowledgment error... ähnelt.
        /// </summary>
        internal static string CANErrorAcknowledge {
            get {
                return ResourceManager.GetString("CANErrorAcknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bit error... ähnelt.
        /// </summary>
        internal static string CANErrorBit {
            get {
                return ResourceManager.GetString("CANErrorBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CRC error... ähnelt.
        /// </summary>
        internal static string CANErrorCRC {
            get {
                return ResourceManager.GetString("CANErrorCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error sending filter disable command ähnelt.
        /// </summary>
        internal static string CANErrorFilterDisable {
            get {
                return ResourceManager.GetString("CANErrorFilterDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die form error... ähnelt.
        /// </summary>
        internal static string CANErrorForm {
            get {
                return ResourceManager.GetString("CANErrorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error sending init command ähnelt.
        /// </summary>
        internal static string CANErrorInitCmd {
            get {
                return ResourceManager.GetString("CANErrorInitCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die other error... ähnelt.
        /// </summary>
        internal static string CANErrorOther {
            get {
                return ResourceManager.GetString("CANErrorOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error reading device version ähnelt.
        /// </summary>
        internal static string CANErrorReadVersion {
            get {
                return ResourceManager.GetString("CANErrorReadVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error setting heartbeat ähnelt.
        /// </summary>
        internal static string CanErrorSetHeartbeat {
            get {
                return ResourceManager.GetString("CanErrorSetHeartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error starting device ähnelt.
        /// </summary>
        internal static string CANErrorStartDevice {
            get {
                return ResourceManager.GetString("CANErrorStartDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error stopping device ähnelt.
        /// </summary>
        internal static string CANErrorStopDevice {
            get {
                return ResourceManager.GetString("CANErrorStopDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stuff error... ähnelt.
        /// </summary>
        internal static string CANErrorStuff {
            get {
                return ResourceManager.GetString("CANErrorStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initialized ähnelt.
        /// </summary>
        internal static string CANInitialized {
            get {
                return ResourceManager.GetString("CANInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN trying reconnection... ähnelt.
        /// </summary>
        internal static string CANReconnect {
            get {
                return ResourceManager.GetString("CANReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Received remote frame ?!? ähnelt.
        /// </summary>
        internal static string CANRemoteFrame {
            get {
                return ResourceManager.GetString("CANRemoteFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN resetted... ähnelt.
        /// </summary>
        internal static string CANReset {
            get {
                return ResourceManager.GetString("CANReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Re-)starting slave {0} ähnelt.
        /// </summary>
        internal static string CANRestartSlave {
            get {
                return ResourceManager.GetString("CANRestartSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN started... ähnelt.
        /// </summary>
        internal static string CANStart {
            get {
                return ResourceManager.GetString("CANStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN stopped... ähnelt.
        /// </summary>
        internal static string CANStop {
            get {
                return ResourceManager.GetString("CANStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string DialogButtonCancel {
            get {
                return ResourceManager.GetString("DialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        internal static string DialogButtonOk {
            get {
                return ResourceManager.GetString("DialogButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU Process Variables ähnelt.
        /// </summary>
        internal static string DialogProcVarsTabECU {
            get {
                return ResourceManager.GetString("DialogProcVarsTabECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast Process Variables ähnelt.
        /// </summary>
        internal static string DialogProcVarsTabMast {
            get {
                return ResourceManager.GetString("DialogProcVarsTabMast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process Variables ähnelt.
        /// </summary>
        internal static string DialogProcVarsTitle {
            get {
                return ResourceManager.GetString("DialogProcVarsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter password ähnelt.
        /// </summary>
        internal static string DialogPWCaption {
            get {
                return ResourceManager.GetString("DialogPWCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid password! ähnelt.
        /// </summary>
        internal static string DialogPWInvalid {
            get {
                return ResourceManager.GetString("DialogPWInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password required ähnelt.
        /// </summary>
        internal static string DialogPWTitle {
            get {
                return ResourceManager.GetString("DialogPWTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter valid values before saving! ähnelt.
        /// </summary>
        internal static string DialogSettingsInvalidData {
            get {
                return ResourceManager.GetString("DialogSettingsInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU Settings ähnelt.
        /// </summary>
        internal static string DialogSettingsTabECU {
            get {
                return ResourceManager.GetString("DialogSettingsTabECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast Settings ähnelt.
        /// </summary>
        internal static string DialogSettingsTabMast {
            get {
                return ResourceManager.GetString("DialogSettingsTabMast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string DialogSettingsTitle {
            get {
                return ResourceManager.GetString("DialogSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutting down CAN driver, this may take a while... ähnelt.
        /// </summary>
        internal static string DialogShutdownMessage {
            get {
                return ResourceManager.GetString("DialogShutdownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown CAN driver ähnelt.
        /// </summary>
        internal static string DialogShutdownTitle {
            get {
                return ResourceManager.GetString("DialogShutdownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting CAN driver, this may take a while... ähnelt.
        /// </summary>
        internal static string DialogStartupMessage {
            get {
                return ResourceManager.GetString("DialogStartupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting CAN driver ähnelt.
        /// </summary>
        internal static string DialogStartupTitle {
            get {
                return ResourceManager.GetString("DialogStartupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU 1 ähnelt.
        /// </summary>
        internal static string ECU1 {
            get {
                return ResourceManager.GetString("ECU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU 2 ähnelt.
        /// </summary>
        internal static string ECU2 {
            get {
                return ResourceManager.GetString("ECU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU 3 ähnelt.
        /// </summary>
        internal static string ECU3 {
            get {
                return ResourceManager.GetString("ECU3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU 4 ähnelt.
        /// </summary>
        internal static string ECU4 {
            get {
                return ResourceManager.GetString("ECU4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU 5 ähnelt.
        /// </summary>
        internal static string ECU5 {
            get {
                return ResourceManager.GetString("ECU5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU {0}: Emergency Stop ähnelt.
        /// </summary>
        internal static string ErrorEmergencyStop {
            get {
                return ResourceManager.GetString("ErrorEmergencyStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast {0} Encoder: CAN Timeout ähnelt.
        /// </summary>
        internal static string ErrorEncoderCanTimeout {
            get {
                return ResourceManager.GetString("ErrorEncoderCanTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU {0}: External temperature sensor: Invalid signal ähnelt.
        /// </summary>
        internal static string ErrorExtTempSensor {
            get {
                return ResourceManager.GetString("ErrorExtTempSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannnot read setting for {0} in section {1} from MastControl.ini ähnelt.
        /// </summary>
        internal static string ErrorIniFile {
            get {
                return ResourceManager.GetString("ErrorIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU {0}: Internal CAN not working ähnelt.
        /// </summary>
        internal static string ErrorLocalCAN {
            get {
                return ResourceManager.GetString("ErrorLocalCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast {0} motor controller: Fault ähnelt.
        /// </summary>
        internal static string ErrorMastErrorFU {
            get {
                return ResourceManager.GetString("ErrorMastErrorFU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast {0} motor controller: CAN timeout ähnelt.
        /// </summary>
        internal static string ErrorMastFUCanTimeout {
            get {
                return ResourceManager.GetString("ErrorMastFUCanTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast {0} height sensor: Out of range ähnelt.
        /// </summary>
        internal static string ErrorMastHeightOutOfRange {
            get {
                return ResourceManager.GetString("ErrorMastHeightOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast {0}: Limit switch bottom position ähnelt.
        /// </summary>
        internal static string ErrorMastLimitSwitchBottom {
            get {
                return ResourceManager.GetString("ErrorMastLimitSwitchBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast {0}: Limit switch top position ähnelt.
        /// </summary>
        internal static string ErrorMastLimitSwitchTop {
            get {
                return ResourceManager.GetString("ErrorMastLimitSwitchTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast {0}: Not ready to switch on ähnelt.
        /// </summary>
        internal static string ErrorMastNotReadyToSwitchOn {
            get {
                return ResourceManager.GetString("ErrorMastNotReadyToSwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast {0}  state machine: Error state {1} ähnelt.
        /// </summary>
        internal static string ErrorMastStateMachine {
            get {
                return ResourceManager.GetString("ErrorMastStateMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast {0}: Invalid position difference (absolute encoder / FU) ähnelt.
        /// </summary>
        internal static string ErrorPositionDifference {
            get {
                return ResourceManager.GetString("ErrorPositionDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU {0}: Temperature sensor cabinet: Invalid signal ähnelt.
        /// </summary>
        internal static string ErrorTemperatureSensor {
            get {
                return ResourceManager.GetString("ErrorTemperatureSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU {0}: Wind sensor: Invalid signal ähnelt.
        /// </summary>
        internal static string ErrorWindSensor {
            get {
                return ResourceManager.GetString("ErrorWindSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blackout ähnelt.
        /// </summary>
        internal static string MainWindowBlackout {
            get {
                return ResourceManager.GetString("MainWindowBlackout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug ähnelt.
        /// </summary>
        internal static string MainWindowBottomTabItemDebug {
            get {
                return ResourceManager.GetString("MainWindowBottomTabItemDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error messages ähnelt.
        /// </summary>
        internal static string MainWindowBottomTabItemErrors {
            get {
                return ResourceManager.GetString("MainWindowBottomTabItemErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string MainWindowInfoRectErrorLED {
            get {
                return ResourceManager.GetString("MainWindowInfoRectErrorLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operational ähnelt.
        /// </summary>
        internal static string MainWindowInfoRectOkLED {
            get {
                return ResourceManager.GetString("MainWindowInfoRectOkLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string MainWindowMenuExit {
            get {
                return ResourceManager.GetString("MainWindowMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string MainWindowMenuFile {
            get {
                return ResourceManager.GetString("MainWindowMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string MainWindowMenuLanguage {
            get {
                return ResourceManager.GetString("MainWindowMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process Variables ähnelt.
        /// </summary>
        internal static string MainWindowMenuProcVars {
            get {
                return ResourceManager.GetString("MainWindowMenuProcVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string MainWindowMenuSettings {
            get {
                return ResourceManager.GetString("MainWindowMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show error messages list ähnelt.
        /// </summary>
        internal static string MainWindowMenuShowErrors {
            get {
                return ResourceManager.GetString("MainWindowMenuShowErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        internal static string MainWindowMenuTools {
            get {
                return ResourceManager.GetString("MainWindowMenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU not connected! ähnelt.
        /// </summary>
        internal static string MainWindowMsgECUNotConnected {
            get {
                return ResourceManager.GetString("MainWindowMsgECUNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application already running! ähnelt.
        /// </summary>
        internal static string MainWindowSingleInstance {
            get {
                return ResourceManager.GetString("MainWindowSingleInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast Control Pandur V0.6 ähnelt.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAN-Status ähnelt.
        /// </summary>
        internal static string MainWindowTitleBarCANStatus {
            get {
                return ResourceManager.GetString("MainWindowTitleBarCANStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string MainWindowTitleBarError {
            get {
                return ResourceManager.GetString("MainWindowTitleBarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string MainWindowTitleBarReset {
            get {
                return ResourceManager.GetString("MainWindowTitleBarReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wind speed: {0} km/h ähnelt.
        /// </summary>
        internal static string MainWindowTitleBarWindspeed {
            get {
                return ResourceManager.GetString("MainWindowTitleBarWindspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 1 ähnelt.
        /// </summary>
        internal static string Mast1 {
            get {
                return ResourceManager.GetString("Mast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 2 ähnelt.
        /// </summary>
        internal static string Mast2 {
            get {
                return ResourceManager.GetString("Mast2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 3 ähnelt.
        /// </summary>
        internal static string Mast3 {
            get {
                return ResourceManager.GetString("Mast3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 4 ähnelt.
        /// </summary>
        internal static string Mast4 {
            get {
                return ResourceManager.GetString("Mast4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 5 ähnelt.
        /// </summary>
        internal static string Mast5 {
            get {
                return ResourceManager.GetString("Mast5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ECU ähnelt.
        /// </summary>
        internal static string MastControlledByECU {
            get {
                return ResourceManager.GetString("MastControlledByECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Named Pipe ähnelt.
        /// </summary>
        internal static string MastControlledByNAMEDPIPE {
            get {
                return ResourceManager.GetString("MastControlledByNAMEDPIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string MastControlledByNONE {
            get {
                return ResourceManager.GetString("MastControlledByNONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PC ähnelt.
        /// </summary>
        internal static string MastControlledByPC {
            get {
                return ResourceManager.GetString("MastControlledByPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug: ähnelt.
        /// </summary>
        internal static string MsgListDebug {
            get {
                return ResourceManager.GetString("MsgListDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: ähnelt.
        /// </summary>
        internal static string MsgListError {
            get {
                return ResourceManager.GetString("MsgListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum windspeed;km/h ähnelt.
        /// </summary>
        internal static string Param2000_1 {
            get {
                return ResourceManager.GetString("Param2000_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Same time automatic rectracting windspeed;0=OFF 1=ON ähnelt.
        /// </summary>
        internal static string Param2000_10 {
            get {
                return ResourceManager.GetString("Param2000_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delay for windspeed;s ähnelt.
        /// </summary>
        internal static string Param2000_11 {
            get {
                return ResourceManager.GetString("Param2000_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User PW ähnelt.
        /// </summary>
        internal static string Param2000_12 {
            get {
                return ResourceManager.GetString("Param2000_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature threshold low;°C ähnelt.
        /// </summary>
        internal static string Param2000_13 {
            get {
                return ResourceManager.GetString("Param2000_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature threshold high;°C ähnelt.
        /// </summary>
        internal static string Param2000_14 {
            get {
                return ResourceManager.GetString("Param2000_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lead time warning light;s ähnelt.
        /// </summary>
        internal static string Param2000_2 {
            get {
                return ResourceManager.GetString("Param2000_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lead time warning horn;s ähnelt.
        /// </summary>
        internal static string Param2000_3 {
            get {
                return ResourceManager.GetString("Param2000_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature heating ON;°C ähnelt.
        /// </summary>
        internal static string Param2000_4 {
            get {
                return ResourceManager.GetString("Param2000_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature heating OFF;°C ähnelt.
        /// </summary>
        internal static string Param2000_5 {
            get {
                return ResourceManager.GetString("Param2000_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning lights during mast movement;0=OFF 1=ON ähnelt.
        /// </summary>
        internal static string Param2000_6 {
            get {
                return ResourceManager.GetString("Param2000_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning lights in camouflage mode;0=OFF 1=ON ähnelt.
        /// </summary>
        internal static string Param2000_7 {
            get {
                return ResourceManager.GetString("Param2000_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning horn during mast movement;0=OFF 1=ON ähnelt.
        /// </summary>
        internal static string Param2000_8 {
            get {
                return ResourceManager.GetString("Param2000_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning horn in camouflage mode;0=OFF 1=ON ähnelt.
        /// </summary>
        internal static string Param2000_9 {
            get {
                return ResourceManager.GetString("Param2000_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windspeed 1;km/h ähnelt.
        /// </summary>
        internal static string Param2001_1 {
            get {
                return ResourceManager.GetString("Param2001_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windspeed 2;km/h ähnelt.
        /// </summary>
        internal static string Param2001_2 {
            get {
                return ResourceManager.GetString("Param2001_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windspeed 3;km/h ähnelt.
        /// </summary>
        internal static string Param2001_3 {
            get {
                return ResourceManager.GetString("Param2001_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windspeed 4;km/h ähnelt.
        /// </summary>
        internal static string Param2001_4 {
            get {
                return ResourceManager.GetString("Param2001_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windspeed 5;km/h ähnelt.
        /// </summary>
        internal static string Param2001_5 {
            get {
                return ResourceManager.GetString("Param2001_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 1 maximum height for windspeed 1;m ähnelt.
        /// </summary>
        internal static string Param2002_1 {
            get {
                return ResourceManager.GetString("Param2002_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 1 maximum height for windspeed 2;m ähnelt.
        /// </summary>
        internal static string Param2002_2 {
            get {
                return ResourceManager.GetString("Param2002_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 1 maximum height for windspeed 3;m ähnelt.
        /// </summary>
        internal static string Param2002_3 {
            get {
                return ResourceManager.GetString("Param2002_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 1 maximum height for windspeed 4;m ähnelt.
        /// </summary>
        internal static string Param2002_4 {
            get {
                return ResourceManager.GetString("Param2002_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 1 maximum height for windspeed 5;m ähnelt.
        /// </summary>
        internal static string Param2002_5 {
            get {
                return ResourceManager.GetString("Param2002_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 2 maximum height for windspeed 1;m ähnelt.
        /// </summary>
        internal static string Param2003_1 {
            get {
                return ResourceManager.GetString("Param2003_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 2 maximum height for windspeed 2;m ähnelt.
        /// </summary>
        internal static string Param2003_2 {
            get {
                return ResourceManager.GetString("Param2003_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 2 maximum height for windspeed 3;m ähnelt.
        /// </summary>
        internal static string Param2003_3 {
            get {
                return ResourceManager.GetString("Param2003_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 2 maximum height for windspeed 4;m ähnelt.
        /// </summary>
        internal static string Param2003_4 {
            get {
                return ResourceManager.GetString("Param2003_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast 2 maximum height for windspeed 5;m ähnelt.
        /// </summary>
        internal static string Param2003_5 {
            get {
                return ResourceManager.GetString("Param2003_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum valid mast height;mm ähnelt.
        /// </summary>
        internal static string Param2004 {
            get {
                return ResourceManager.GetString("Param2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum valid mast height;mm ähnelt.
        /// </summary>
        internal static string Param2005 {
            get {
                return ResourceManager.GetString("Param2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast height top position;mm ähnelt.
        /// </summary>
        internal static string Param2006 {
            get {
                return ResourceManager.GetString("Param2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast height bottom position;mm ähnelt.
        /// </summary>
        internal static string Param2007 {
            get {
                return ResourceManager.GetString("Param2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voltage top position;V ähnelt.
        /// </summary>
        internal static string Param2008 {
            get {
                return ResourceManager.GetString("Param2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voltage bottom position;V ähnelt.
        /// </summary>
        internal static string Param2009 {
            get {
                return ResourceManager.GetString("Param2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Velocity;rpm ähnelt.
        /// </summary>
        internal static string Param200A {
            get {
                return ResourceManager.GetString("Param200A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Velocity slow speed;rpm ähnelt.
        /// </summary>
        internal static string Param200B {
            get {
                return ResourceManager.GetString("Param200B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Velocity bottom;rpm ähnelt.
        /// </summary>
        internal static string Param200C {
            get {
                return ResourceManager.GetString("Param200C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom position offset;mm ähnelt.
        /// </summary>
        internal static string Param200D {
            get {
                return ResourceManager.GetString("Param200D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current limit bottom;A ähnelt.
        /// </summary>
        internal static string Param200E {
            get {
                return ResourceManager.GetString("Param200E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom limit switch window;mm ähnelt.
        /// </summary>
        internal static string Param200F {
            get {
                return ResourceManager.GetString("Param200F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encoder offset;mm ähnelt.
        /// </summary>
        internal static string Param2010 {
            get {
                return ResourceManager.GetString("Param2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast height medium position;mm ähnelt.
        /// </summary>
        internal static string Param2011 {
            get {
                return ResourceManager.GetString("Param2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mast medium position window;mm ähnelt.
        /// </summary>
        internal static string Param2012 {
            get {
                return ResourceManager.GetString("Param2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motor active time;s ähnelt.
        /// </summary>
        internal static string Param2013 {
            get {
                return ResourceManager.GetString("Param2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adjust encoder, magic word (333777333) ähnelt.
        /// </summary>
        internal static string Param2014 {
            get {
                return ResourceManager.GetString("Param2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current limit bottom 10..20°C;A ähnelt.
        /// </summary>
        internal static string Param2015 {
            get {
                return ResourceManager.GetString("Param2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current limit bottom 0..10°C;A ähnelt.
        /// </summary>
        internal static string Param2016 {
            get {
                return ResourceManager.GetString("Param2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current limit bottom -10..0°C;A ähnelt.
        /// </summary>
        internal static string Param2017 {
            get {
                return ResourceManager.GetString("Param2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current limit bottom -20..-10°C;A ähnelt.
        /// </summary>
        internal static string Param2018 {
            get {
                return ResourceManager.GetString("Param2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current limit bottom -30..-20°C;A ähnelt.
        /// </summary>
        internal static string Param2019 {
            get {
                return ResourceManager.GetString("Param2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom window disable current error;1/100mm ähnelt.
        /// </summary>
        internal static string Param201A {
            get {
                return ResourceManager.GetString("Param201A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current limit bottom &lt; -30°C;A ähnelt.
        /// </summary>
        internal static string Param201B {
            get {
                return ResourceManager.GetString("Param201B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reserved ähnelt.
        /// </summary>
        internal static string Param201C {
            get {
                return ResourceManager.GetString("Param201C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reserved ähnelt.
        /// </summary>
        internal static string Param201D {
            get {
                return ResourceManager.GetString("Param201D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reserved ähnelt.
        /// </summary>
        internal static string Param201E {
            get {
                return ResourceManager.GetString("Param201E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reserved ähnelt.
        /// </summary>
        internal static string Param201F {
            get {
                return ResourceManager.GetString("Param201F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Velocity up;rpm ähnelt.
        /// </summary>
        internal static string Param2020 {
            get {
                return ResourceManager.GetString("Param2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Velocity down;rpm ähnelt.
        /// </summary>
        internal static string Param2021 {
            get {
                return ResourceManager.GetString("Param2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windspeed;km/h ähnelt.
        /// </summary>
        internal static string Param3000_3 {
            get {
                return ResourceManager.GetString("Param3000_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cabinet Temperature;°C ähnelt.
        /// </summary>
        internal static string Param3000_4 {
            get {
                return ResourceManager.GetString("Param3000_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die External Temperature;°C ähnelt.
        /// </summary>
        internal static string Param3000_5 {
            get {
                return ResourceManager.GetString("Param3000_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal Voltage;V ähnelt.
        /// </summary>
        internal static string Param3000_6 {
            get {
                return ResourceManager.GetString("Param3000_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height;mm ähnelt.
        /// </summary>
        internal static string Param3001 {
            get {
                return ResourceManager.GetString("Param3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed;mm/s ähnelt.
        /// </summary>
        internal static string Param3002 {
            get {
                return ResourceManager.GetString("Param3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voltage;V ähnelt.
        /// </summary>
        internal static string Param3005 {
            get {
                return ResourceManager.GetString("Param3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current;A ähnelt.
        /// </summary>
        internal static string Param3006 {
            get {
                return ResourceManager.GetString("Param3006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Torque;Nm ähnelt.
        /// </summary>
        internal static string Param3007 {
            get {
                return ResourceManager.GetString("Param3007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load;% ähnelt.
        /// </summary>
        internal static string Param3008 {
            get {
                return ResourceManager.GetString("Param3008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height sensor;V ähnelt.
        /// </summary>
        internal static string Param3009 {
            get {
                return ResourceManager.GetString("Param3009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature Power Stage;°C ähnelt.
        /// </summary>
        internal static string Param300A {
            get {
                return ResourceManager.GetString("Param300A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature Controller;°C ähnelt.
        /// </summary>
        internal static string Param300B {
            get {
                return ResourceManager.GetString("Param300B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zwischenkreisspannung;V ähnelt.
        /// </summary>
        internal static string Param300C {
            get {
                return ResourceManager.GetString("Param300C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startup error code ähnelt.
        /// </summary>
        internal static string Param300E {
            get {
                return ResourceManager.GetString("Param300E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature Amplifier;°C ähnelt.
        /// </summary>
        internal static string Param300F {
            get {
                return ResourceManager.GetString("Param300F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FU error code ähnelt.
        /// </summary>
        internal static string Param3010 {
            get {
                return ResourceManager.GetString("Param3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encoder digits ähnelt.
        /// </summary>
        internal static string Param3011 {
            get {
                return ResourceManager.GetString("Param3011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State ähnelt.
        /// </summary>
        internal static string Param3012 {
            get {
                return ResourceManager.GetString("Param3012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Velocity;rpm ähnelt.
        /// </summary>
        internal static string Param3013 {
            get {
                return ResourceManager.GetString("Param3013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motor active time;s ähnelt.
        /// </summary>
        internal static string Param3014 {
            get {
                return ResourceManager.GetString("Param3014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height;1/100mm ähnelt.
        /// </summary>
        internal static string Param3015 {
            get {
                return ResourceManager.GetString("Param3015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        internal static string Param3020_1 {
            get {
                return ResourceManager.GetString("Param3020_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build date ähnelt.
        /// </summary>
        internal static string Param3020_2 {
            get {
                return ResourceManager.GetString("Param3020_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slow ähnelt.
        /// </summary>
        internal static string SlowSpeed {
            get {
                return ResourceManager.GetString("SlowSpeed", resourceCulture);
            }
        }
    }
}
